# Generated by Django 4.0.5 on 2022-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(default='a', max_length=180),
            preserve_default=False,
        ),
    ]
